# Q1: Import numpy library

In [1]:
import numpy as np 

# Q2: Generate a sequence of 15 floats using linspace() function

In [14]:
sequence = np.linspace(0, 10, 15)

print(sequence)

[ 0.     0.714  1.429  2.143  2.857  3.571  4.286  5.     5.714  6.429
  7.143  7.857  8.571  9.286 10.   ]


# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [16]:
arr1 = np.array([1.1, 2.1, 3.1])
arr2 = np.array([4.1, 5.1, 6.1])
arr3 = np.array([7.1, 8.1, 9.1])
arr4 = np.array([10.1, 11.1, 12.1])

D3_array = np.array([[arr1, arr2], [arr3, arr4]])

print(D3_array)

[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [22]:
print("Array's type:", type(D3_array))
print("Arrays datatype :", D3_array.dtype)
print("Arrays shape :", D3_array.shape)
print("Arrays size :", D3_array.size)
print("Arrays dimension :", D3_array.ndim)

Array's type: <class 'numpy.ndarray'>
Arrays datatype : float64
Arrays shape : (2, 2, 3)
Arrays size : 12
Arrays dimension : 3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [66]:
D4_array = D3_array.reshape(1, 2, 2, 3)

print("D4_array dimension:", D4_array.ndim)
print("D4_array shape:", D4_array.shape)
print()
print(D4_array)


D4_array dimension: 4
D4_array shape: (1, 2, 2, 3)

[[[[ 1.1  2.1  3.1]
   [ 4.1  5.1  6.1]]

  [[ 7.1  8.1  9.1]
   [10.1 11.1 12.1]]]]


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [36]:
int_D4_array = D4_array.astype(int)

print(int_D4_array)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [40]:
for e in np.nditer(int_D4_array):
    print(e)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [44]:
number_8 = int_D4_array[0, 1, 0, 1]
print(number_8)

8


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [46]:
# Extract and print the numbers 5 and 6 using array slicing
number_5 = int_D4_array[0, 0, 1, 1]  # Extract number 5
number_6 = int_D4_array[0, 0, 1, 2]  # Extract number 6

print("Number 5:", number_5)
print("Number 6:", number_6)

Number 5: 5
Number 6: 6


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [54]:
indices = np.where(int_D4_array == 8)

index_path = list(zip(indices[0], indices[1], indices[2], indices[3]))

print("Index path of  8:", index_path)

Index path of  8: [(0, 1, 0, 1)]


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [58]:
resh_array = np.reshape(int_D4_array, (2, 3, 2))

print(resh_array)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [72]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

join_arr = np.concatenate((arr1, arr2))

print(join_arr)

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [74]:
join_arr = np.concatenate((array1, array2), axis=1)

print(join_arr)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [76]:
split_arrays = np.split(join_arr, 2, axis=1)

for arr in split_arrays:
    print(arr)

[['A' 'B']
 ['E' 'F']]
[['C' 'D']
 ['G' 'H']]
