In [3]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [19]:
x = np.ones(4)
print(x)

[1. 1. 1. 1.]


## Q#2: Create y array with elements equal to 0.

In [21]:
y = np.zeros(4)
print(y)

[0. 0. 0. 0.]


## Q#3: Add x and y arrays.

In [51]:
x_y = np.add(x, y)
print(x_y)

[1. 1. 1. 1.]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [41]:
print("Dimension :", x.ndim)
print("Shape :", x.shape)
print("Size :", x.size)
print("Type :", x.dtype)


Dimension : 1
Shape : (4,)
Size : 4
Type : float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [49]:
w = np.array([[11, 12], [13, 14], [15, 16]])
print(w)

[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [55]:
z = np.array(range(1,4))
print(z)

[1 2 3]


## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [121]:
newArray = np.hstack((z.reshape(-1, 1), w))
print(newArray)

[[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]


## Q#8: Print all elements of "newArray" using the loop.

In [66]:
print("All elements of 'newArray':")
for r in newArray:
    for c in r:
        print(c)

All elements of 'newArray':
1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [70]:
revArray = np.flip(np.flip(newArray, axis=0), axis=1)

print(revArray)

[[16 15  3]
 [14 13  2]
 [12 11  1]]


## Q#10: Decrement all elements of "newArray" with 1.

In [137]:
Dec_newArray = newArray - 1

print(Dec_newArray)

[[ 0 10 11]
 [ 1 12 13]
 [ 2 14 15]]


## Q#11: Find smallest and biggest values in "newArray".

In [78]:
min_value = np.min(newArray)
max_value = np.max(newArray)

print("Smallest value :", min_value)
print("Largest value :", max_value)

Smallest value : 0
Largest value : 15


## Q#12: Print the first row of "newArray" using indexing.

In [94]:
first_row = newArray[0]

print(first_row)

[ 0 10 11]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [107]:
number_12 = newArray[np.where(newArray == 12)]

print(number_12)

[12]


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [105]:
number_0 = newArray[np.where(newArray == 0)]

number_13 = newArray[np.where(newArray == 13)]

print(number_0)
print(number_13)


[0]
[13]


## Q#15: Change the shape of "newArray" to (9,1).

In [90]:
newArray_resh = newArray.reshape(9, 1)

print(newArray_resh)

[[ 0]
 [10]
 [11]
 [ 1]
 [12]
 [13]
 [ 2]
 [14]
 [15]]


## Q#16: Change the shape of "newArray" to (3,2).

In [151]:
newArray_reshaped = w.reshape(3, 2)

print(newArray_reshaped)

[[11 12]
 [13 14]
 [15 16]]


# Well Done 🎉